#ifndef NEXTHA_ERRORS_H
#define NEXTHA_ERRORS_H

enum {
    HA_OK = 0,
    ERR_TP_ESP_NONE = -1, ERR_TP_ESP_INIT = -2, ERR_TP_CONNECT = -3, ERR_TP_TIMEOUT = -4, ERR_TP_SEND = -5, ERR_TP_BREAK = -6,
    ERR_HTTP_STATUS = -10, ERR_HTTP_TRUNCATED = -11, ERR_HTTP_CHUNKED = -12, ERR_HTTP_BADLEN = -13,
    ERR_HA_AUTH = -20, ERR_HA_STATUS = -21, ERR_HA_TEMPLATE = -22,
    ERR_CFG_MISSING = -30, ERR_CFG_KEY = -31, ERR_CFG_TOOLONG = -32,
    ERR_ARG_USAGE = -40, ERR_ARG_BANK = -41, ERR_ARG_LEN = -42
};

#endif
